/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sat;

import org.junit.jupiter.api.Test;

import sat.SAT;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        SAT classUnderTest = new SAT();
        assertNotNull(classUnderTest.call(), "app should have a greeting");
    }
}
